# -*- coding: utf-8 -*-
"""Mouse dynamics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/kitty4016/mouse-dynamics.effb6717-b770-42c1-9bc6-919c7d1f6f3a.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250605/auto/storage/goog4_request%26X-Goog-Date%3D20250605T064843Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6ef71e436532eaaf3f6777d8e08f2c1fbc9f7cb6d4ce5e0e61747fd7e36686da8010f9d0d8a23e67a7f8ba8103451a783eb85b365c4851b2dd696c2e582843b8a23dce7f0675cd69a390f51db4589286eec763228b30cab1464c217bcfb0e74a110b083f085e89fa327c2dba223134d53bb661cfaa4e0a66f8e92018aed66a8c7bd66155c404fb83c11382c8aa04c3392ce33c6a8bac441537f8d18b6f59e010fbde06a75212b300dad6e8f627c35d62d572ca3a98e50b83f2d053eeb19b301e09df6ad34e3825084b23257c299aeb39e59949f981cf1e45f4471a6a959372b0658e2363e89809ca628855e59ea45948cfb747ba27d6645352a22bd4dd4e8bc5
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
jaafarnejm_mouse_dynamics_for_user_authentication_path = kagglehub.dataset_download('jaafarnejm/mouse-dynamics-for-user-authentication')

print('Data source import complete.')

"""# Mouse dynamics
## User identification based on mouse activity fingerprint
### Author: Nejm Jaafar - Data scientist

<h3> Introduction:</h3>


In this notebook, we will analyze mouse event data with the aim to identify the user. <br>Mouse Dynamics is a behavioral biometrics technology used to validate a user's identity by analyzing unique patterns - such as tiny hand motions - detected in the user's interaction with their mouse or pointer. Mouse dynamics algorithms interpret the data gathered from a mouse or pointer to build a unique user profile. Mouse dynamics in authentication is essentially being able to validate someone's identity by the way they use their mouse.<br>
<h4> Datasets:</h4>

• Train_Mouse.csv: In this dataset, the mouse events data from 20 users are collected.<br>
The mouse events are collected during user interaction with a demo banking application. Each user is asked to do 6 sessions and for each session, the data of mouse events are collected. Each row of the dataset represents a single mouse event and consists of uid (unique identifier for each mouse event), session_id (session identifier), user_id, timestamp, event_type (mouse movement type), screen_x and screen_y (coordinates of the mouse event).<br>
Every row of the mouse event data has an event_type column that shows what kind of mouse event the row represents. However, every row by itself does not represent the entire event, the event if oftentimes represented by multiple events in a row. <br>For example, a drag event is a event_type 4 (drag) followed by an indeterminate amount of event_type's 2 (move) and ends with a event_type 1 (release).<br><br>
The different event_type's recorded are:
- 1 = release
- 2 = move
- 3 = wheel
- 4 = drag
- 5 = click

And the different events that can occur are:
- click – one click event_type (5) followed by one release event_type (1)
- move – indeterminate amount of move event_type's (2)
- drag – one drag event_type (4) followed by indeterminate amount of move event_type's (2) ending with one release event_type (1)
- wheel – indeterminate amount of wheel event_type's (3)

• Test_Mouse.csv: This dataset has the same structure as the Train dataset except that the user_id is not included.
<h4> Objective:</h4>

Determine UserID for each session_id in "Test_Mouse.csv" dataset based on collected mouse events data.

<h4> Content:</h4>

We will go through 4 major parts:
- EDA that covers real simulation of the mouse, showing the exact path it took on the screen (space), plus temporal analysis for the user's session time.
- Feature engineering part during which I derived insights from the X-Y-T and converted them into indicative features like slope, tightness, centers, frequencies, etc.
- Model training, which shows the transformations of the dataset and running the multilayer perceptron classifier (Neural network).
- Evaluation of the model using F1 score and confusion matrix, and introducing cross validation to reduce the over-fitting.
- Generating the users IDs for the Test_mouse.csv file.
- Conclusion and perspectives.

We will use <b>Spark</b> for this implementation.
"""



"""##### import libraries"""


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import seaborn as sn
import hashlib
import binascii
import math
import os
from sklearn.decomposition import PCA as skPCA
from pyspark.ml.feature import PCA as spPCA
from pyspark.ml.linalg import Vectors
from pyspark.ml.tuning import CrossValidator, TrainValidationSplit, ParamGridBuilder, TrainValidationSplitModel
from pyspark.ml.feature import VectorAssembler, MinMaxScaler
from pyspark.ml.classification import MultilayerPerceptronClassifier, GBTClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
from pyspark.sql.types import StructType, StringType, FloatType, LongType, IntegerType, StructField
from pyspark.sql import HiveContext, SparkSession
from pyspark.sql.functions import countDistinct, array_distinct, col, isnan, when, count, lit, array
import pickle

plt.rcParams["figure.autolayout"] = True

"""### EDA"""

# Define paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, 'data')
MODEL_DIR = os.path.join(BASE_DIR, 'models')
SCALER_DIR = os.path.join(BASE_DIR, 'scalers')

# Create directories if they don't exist
for dir_path in [DATA_DIR, MODEL_DIR, SCALER_DIR]:
    os.makedirs(dir_path, exist_ok=True)

# Initialize spark context
spark = SparkSession.builder.appName("MouseDynamics").getOrCreate()

# Define schema for mouse data
schemaMousePos = StructType([
    StructField('uid', StringType(), False,),
    StructField('session_id', StringType(), False),
    StructField('user_id', StringType(), True),
    StructField('timestamp', LongType(), False),
    StructField('event_type', IntegerType(), False),
    StructField('screen_x', FloatType(), False),
    StructField('screen_y', FloatType(), False)
])

# Load training data - using the file in current directory since it was downloaded there
trainDs = spark.read.csv('Train_Mouse.csv', header=True, schema=schemaMousePos)

# Create user encoder
usersEncoder = {k:i for i,k in enumerate(trainDs.select('user_id').rdd.flatMap(lambda x: x).distinct().collect())}

# Define schema for features
schemaFeatures = StructType([
    StructField('session_id', StringType(), False),
    StructField('user_id', StringType(), True),
    StructField('user_enc', FloatType(), True),
    StructField('center_x', FloatType(), False),
    StructField('center_y', FloatType(), False),
    StructField('center_click_x', FloatType(), False),
    StructField('center_click_y', FloatType(), False),
    StructField('first_x', FloatType(), False),
    StructField('first_y', FloatType(), False),
    StructField('radius', FloatType(), False),
    StructField('slope', FloatType(), False),
    StructField('narrow', FloatType(), False),
    StructField('ev1', FloatType(), False),
    StructField('ev2', FloatType(), False),
    StructField('ev3', FloatType(), False),
    StructField('ev4', FloatType(), False),
    StructField('ev5', FloatType(), False),
    StructField('stress', IntegerType(), False),
    StructField('chill', IntegerType(), False),
    StructField('nbpoints', IntegerType(), False),
])

def featurize(recordsIn):
    session_id, user_id = recordsIn[0]
    records = recordsIn[1]

    center = (lambda axisList: sum(axisList)/len(axisList))
    maxRadius = (lambda xc,yc,xList,yList: max([math.sqrt((xi-xc)**2+(yi-yc)**2) for xi, yi in zip(xList,yList)]))
    eventRatio = (lambda evKey, allEvents: len([1 for e in allEvents if e==evKey])/len(allEvents))

    minSpeed = (lambda timestamps: min([timestamps[i+1]-timestamps[i] for i in range(len(timestamps)-1)]))
    maxSpeed = (lambda timestamps: max([timestamps[i+1]-timestamps[i] for i in range(len(timestamps)-1)]))

    def slope(xList, yList):
        x_avg = sum(xList)/len(xList)
        y_avg = sum(xList)/len(yList)
        u=sum([(xi-x_avg)*(yi-y_avg) for xi, yi in zip(xList,yList)])
        d=sum([(xi-x_avg)**2 for xi in xList])
        return u/d

    def narrow_sklearn(xList, yList):
        X = np.array([[xi,yi] for xi, yi in zip(xList, yList)])
        pca = skPCA(n_components=1)
        pca.fit(X)
        return pca.explained_variance_ratio_[0]

    xList = [record['screen_x'] for record in records]
    yList = [record['screen_y'] for record in records]
    
    centerX = center(xList)
    centerY = center(yList)
    centerClickX = center((lambda x: x if x else [0])([record['screen_x'] for record in records if record['event_type']==5]))
    centerClickY = center((lambda x: x if x else [0])([record['screen_y'] for record in records if record['event_type']==5]))
    firstX = xList[0]
    firstY = yList[0]
    tangentCircleRadius = maxRadius(centerX,centerY,xList,yList)
    slop = slope(xList, yList)
    nar = float(narrow_sklearn(xList, yList))

    allEvents = [record['event_type'] for record in records]
    ev1,ev2,ev3,ev4,ev5 = [eventRatio(i, allEvents) for i in range(1,6)]
    stress = minSpeed(sorted([record['timestamp'] for record in records if record['event_type']==2]))
    chill = maxSpeed(sorted([record['timestamp'] for record in records if record['event_type']==2]))
    nbpoints = len(xList)

    if user_id:
        userEnc = float(usersEncoder[user_id])
    else:
        userEnc = None

    return session_id, user_id, userEnc, centerX, centerY, centerClickX, centerClickY, firstX, firstY, tangentCircleRadius, slop, nar, ev1, ev2, ev3, ev4, ev5, stress, chill, nbpoints

# Create features dataframe
featuresDataframe = spark.createDataFrame(
    trainDs.rdd.groupBy(lambda x: (x['session_id'], x['user_id'])).map(featurize), 
    schema=schemaFeatures
)

# Prepare features for training
in_col = ['center_x', 'center_y', 'center_click_x', 'center_click_y', 'first_x', 'first_y', 
          'radius', 'slope', 'narrow', 'ev1', 'ev2', 'ev3', 'ev4', 'ev5', 'stress', 'chill', 'nbpoints']
nbusers = featuresDataframe.select('user_enc').distinct().count()

# Assemble and scale features
assemble = VectorAssembler(inputCols=in_col, outputCol='assembled_features', handleInvalid='error')
a_data = assemble.transform(featuresDataframe)
scaler = MinMaxScaler(min=0.0, max=1.0, inputCol='assembled_features', outputCol='features')
fittedScaler = scaler.fit(a_data)
s_data = fittedScaler.transform(a_data)

# Split data
train_df, test_df = s_data.select('user_enc','features').randomSplit([0.80,0.20], 89)

# Train model
mlpc = MultilayerPerceptronClassifier(
    featuresCol='features',
    labelCol='user_enc',
    layers=[len(in_col), 40, nbusers],
    maxIter=30000,
    blockSize=8,
    seed=7,
    solver='gd'
)

# Train with cross validation
grid = ParamGridBuilder().addGrid(mlpc.layers, [[len(in_col),50,nbusers],[len(in_col),40,30,nbusers]]).build()
evaluator = MulticlassClassificationEvaluator(labelCol='user_enc', predictionCol='prediction', metricName='f1')
cv = CrossValidator(estimator=mlpc, estimatorParamMaps=grid, evaluator=evaluator, parallelism=2)
cvModel = cv.fit(train_df)

# Evaluate model
pred = cvModel.transform(test_df)
ann_f1 = evaluator.evaluate(pred)
print('Test F1 =', ann_f1)

# Save model
model_path = os.path.join(MODEL_DIR, 'mouse_dynamics_model')
cvModel.save(model_path)

# Save scaler
scaler_path = os.path.join(SCALER_DIR, 'mouse_dynamics_scaler')
fittedScaler.save(scaler_path)

# Save user encoder
encoder_path = os.path.join(MODEL_DIR, 'user_encoder.pkl')
with open(encoder_path, 'wb') as f:
    pickle.dump(usersEncoder, f)

print("Model training completed and saved!")
print(f"Training data loaded from: Train_Mouse.csv")
print(f"Model saved to: {model_path}")
print(f"Scaler saved to: {scaler_path}")
print(f"Encoder saved to: {encoder_path}")

# Stop Spark session
spark.stop()

"""##### Let's have a look at some features"""

df_featued = featuresDataframe.toPandas()
for userId in usersEncoder.keys():
    portionDf = df_featued[df_featued['user_id']==userId]
    for session in portionDf['session_id'].unique():
        portionDfSession = portionDf[portionDf['session_id']==session]
        plt.scatter([1,2,3,4,5],portionDfSession[['ev1','ev2','ev3','ev4','ev5']])
    print(usersEncoder[userId], userId)
    plt.show()

"""##### We can distinguish the user 0 from 17 only by looking at event type ev3!

"""

# TODO: visualize more features



"""### MODEL TRAINING"""

# we compose our features vector column
in_col = ['center_x', 'center_y', 'center_click_x', 'center_click_y', 'first_x', 'first_y', 'radius', 'slope', 'narrow', 'ev1', 'ev2', 'ev3', 'ev4', 'ev5', 'stress', 'chill', 'nbpoints']
nbusers = featuresDataframe.select('user_enc').distinct().count()
assemble = VectorAssembler(inputCols=in_col, outputCol='assembled_features', handleInvalid='error')
a_data = assemble.transform(featuresDataframe)
scaler = MinMaxScaler(min=0.0, max=1.0, inputCol='assembled_features', outputCol='features')
fittedScaler = scaler.fit(a_data)
s_data = fittedScaler.transform(a_data)

# train-test split. (note that the state 89 is selected because it allows all 20 users on test with such a small 20% share)
train_df,test_df = s_data.select('user_enc','features').randomSplit([0.80,0.20],89)
print(train_df.select('user_enc').distinct().count())
print(test_df.select('user_enc').distinct().count())
mlpc=MultilayerPerceptronClassifier( featuresCol='features',labelCol='user_enc',layers = [len(in_col),40,nbusers],maxIter=30000,blockSize=8,seed=7,solver='gd')
ann = mlpc.fit(train_df)

# save the trained model for later
ann.save('/kaggle/working/mlp_71_model')

"""### PERFORMANCE EVALUATION"""

evaluator = MulticlassClassificationEvaluator(labelCol='user_enc',predictionCol='prediction',metricName='f1')

# confusion matrix
def pltConfusion(pred):
    array = np.zeros((nbusers,nbusers), int)
    for k in pred.collect():
        array[int(k['user_enc']),int(k['prediction'])] = array[int(k['user_enc']),int(k['prediction'])]+1
    df_cm = pd.DataFrame(array, range(nbusers), range(nbusers))
    plt.figure(figsize=(10,7))
    sn.set(font_scale=1.4)
    sn.heatmap(df_cm, annot=True, annot_kws={"size": 16})
    plt.show()

# Visualizing the train performance just for reference
pred = ann.transform(train_df)
ann_f1 = evaluator.evaluate(pred)
print('Train F1 =', ann_f1)
pltConfusion(pred)

# The more important part:
pred = ann.transform(test_df)
ann_f1 = evaluator.evaluate(pred)
print('Test F1 =', ann_f1)
pltConfusion(pred)

"""We notice that the model mistakes with the kinda similar patterns, for example it preficts 2 as 16 because they both have linear slim shape.
<br> This might be improved by introducing even more features or feeding more train data.
<br> It also looks like fell for over-fitting. Let's try to fix it..
"""

# We'll apply cross validation, with a grid search to see if it can improve
grid = ParamGridBuilder().addGrid(mlpc.layers, [[len(in_col),50,nbusers],[len(in_col),40,30,nbusers]]).build()
evaluator = MulticlassClassificationEvaluator(labelCol='user_enc',predictionCol='prediction',metricName='f1')
cv = CrossValidator(estimator=mlpc, estimatorParamMaps=grid, evaluator=evaluator, parallelism=2)
cvModel = cv.fit(train_df)

cvModel.getNumFolds()

cvModel.avgMetrics[0]

pred = cvModel.transform(train_df)
ann_f1 = evaluator.evaluate(pred)
print('Train F1 =', ann_f1)
pltConfusion(pred)

pred = cvModel.transform(test_df)
ann_f1 = evaluator.evaluate(pred)
print('Test F1 =', ann_f1)
pltConfusion(pred)

"""Well, the F1 score of test data didn't improve after applying cross validation.
<br> In this case we can test other models like GBT, add more features, and increase the data (either by getting real data or performing some data augmentation)
"""

cvModel.bestModel.getLayers()

cvModel.save('/kaggle/working/cv_70_model')

pred.show(30)

"""### PREDICT TEST"""

schemaMousePosTs = StructType([
    StructField('uid', StringType(), False,),
    StructField('session_id', StringType(), False),
    StructField('timestamp', LongType(), False),
    StructField('event_type', IntegerType(), False),
    StructField('screen_x', FloatType(), False),
    StructField('screen_y', FloatType(), False),
    StructField('user_id', StringType(), True)
])
testDs = spark.read.csv('/kaggle/input/mouse-dynamics-for-user-authentication/Test_Mouse.csv',header=True, schema=schemaMousePosTs)
testDs.printSchema()

testDs.show()

testDs.select('session_id').distinct().count()

"""ok so we have 40 sessions to predict"""

featuresDataframeTs = spark.createDataFrame(
    testDs.rdd.groupBy(lambda x: (x['session_id'], x['user_id'])).map(featurize), schema=schemaFeatures
)

a_data_ts = assemble.transform(featuresDataframeTs)
s_data_ts = fittedScaler.transform(a_data_ts)

pred = ann.transform(s_data_ts)

pred.select(['session_id', 'prediction']).show(50)

pred.select('session_id').distinct().count()

pred.select('prediction').distinct().count()

usersDecoder = {v:k for k,v in usersEncoder.items()}

predPd = pred.toPandas()

predPd['user_id'] = predPd['prediction'].apply(lambda x: usersDecoder[int(x)])

predPd[['session_id','user_id']].set_index('session_id')

testDsC = testDs.toPandas().copy()

# now let's save our predictions
testDsC.reset_index().set_index('session_id').drop(columns='user_id', inplace=False).\
join(predPd[['session_id','user_id']].set_index('session_id')).\
reset_index()[['index', 'uid', 'session_id', 'user_id', 'timestamp', 'event_type', 'screen_x', 'screen_y']].\
set_index('index').sort_index().to_csv('/kaggle/working/Predicted_mouse.csv', index=False)

"""### CONCLUSION

##### During this Machine Learning test case we analysed human input data, trained neural network classification model, and tried to guess the identity of the user behind an unseen behaviour.
Although a large gap (25%) between test and training scores has resulted, this gap can pretty well be reduced by trying some of the following techniques:
- Try different combination of the neural network model layers.
- Try to evaluation other classification models.
- Augment the data either by getting more real data or creating some simulations.
- Try to compose independent features with high level of separation among the categories (se should think about the human reflex in this case, that guides the mouse, or also the type of bank forms, etc).
- It'd be also a good idea to try to approach this problem as a timeseries use case, and train some recurrent models.
"""

